### ISSUE TITLE
Installation fails (500 error)

### ISSUE THREAD

**Issue by gjaugustus** [ewallah/moodle-repository_s3bucket#11]
I attempted to install v4.0.3 on my Moodle site (v 4.0.2+ Build 20220805). The file is unpacked and validated, however when I try to proceed, I get a 500 error.

This also happened when I tried to install v3.9.3.

If I delete the s3bucket folder from the repository folder, my site works again.

Please advise. Thanks in advance.

**Comment by ewallah** [comment]
Which version of local_aws are you using?

**Comment by ewallah** [comment]
You should have received 2 warnings during the installation that this plugin needs the local_aws plugin. If you ignore these warnings....
