### ISSUE TITLE
Can we add upload feature in this?

### ISSUE THREAD

**Issue by kewal28** [ewallah/moodle-repository_s3bucket#9]
Instead of selecting the file from s3 teacher can upload the file on s3 and directly linked from s3 to activity.

Can we do this?

**Comment by ewallah** [comment]
Hello @kewal28,

The upload to s3 feature was removed 3 or 4 years ago.  The main reason was privacy: if teachers want to have the data completely outside Moodle, it is not done to have temporary copies on the Moodle instance. 

But it is also not very efficient to upload a file first to Moodle and then move it to s3, there are cheaper (when a file is uploaded to the server instance and needs to be moved to another region, you pay twice) , better (supporting error recovery) and faster (multichannel) ways to get your data on s3.  Large files produce to much timeouts when they are uploaded using https.

R

**Comment by kewal28** [comment]
I am using moodle for 200 to 300 schools with 7 to 8 servers running and my moodle-data folder becomes 8 TB. If not cost-efficient monthly cost around $3000.

I just want to upload the teacher file on s3 and the server from s3 will save cost.
Teacher can browse from s3 itself.

**Comment by ewallah** [comment]
Do you have access to the complete Google drives or DropBox folders of all your teachers and/or students? 

Is [tool_objectfs](https://github.com/catalyst/moodle-tool_objectfs) not a better (automatic) solution for your problem?
